// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AcceptSummaryActionItem(arg1:number,arg2:number,arg3:string):Promise<api.AcceptActionItemResult>;

export function CreateDailyTask(arg1:api.CreateDailyTaskRequest):Promise<api.CreateResponse>;

export function CreateProject(arg1:api.ProjectInput):Promise<api.CreateResponse>;

export function DeleteCompletedTask(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteSummary(arg1:number):Promise<void>;

export function EstimateTaskPreview(arg1:api.EstimatePreviewRequest):Promise<api.EstimatePreviewResponse>;

export function FinishTask(arg1:number,arg2:api.FinishTaskRequest):Promise<void>;

export function GenerateDailySummary(arg1:string):Promise<api.GenerateSummaryResult>;

export function GenerateWeeklySummary(arg1:string,arg2:string):Promise<api.GenerateSummaryResult>;

export function GetDailyStats(arg1:string):Promise<api.DailyStats>;

export function GetPlanRisk(arg1:string):Promise<api.PlanRiskResponse>;

export function GetProject(arg1:number):Promise<api.Project>;

export function GetProjects():Promise<Array<api.Project>>;

export function GetStartupStatus():Promise<api.StartupStatus>;

export function GetSummaries(arg1:string):Promise<Array<api.Summary>>;

export function GetSummary(arg1:number):Promise<api.Summary>;

export function GetWeeklyStats(arg1:string,arg2:string):Promise<api.WeeklyStats>;

export function ListDailyTasks(arg1:string):Promise<Array<api.DailyTask>>;

export function ListMemories(arg1:string,arg2:string,arg3:number):Promise<Array<api.MemoryListItem>>;

export function ListMemoryEvidence(arg1:number):Promise<Array<api.MemoryEvidenceItem>>;

export function PauseTask(arg1:number):Promise<void>;

export function ResumeTask(arg1:number):Promise<void>;

export function StartTask(arg1:number):Promise<void>;

export function SubmitFeedback(arg1:api.FeedbackRequest):Promise<api.FeedbackResponse>;

export function TestLLM():Promise<api.LLMTestResponse>;

export function UpdateCompletedTask(arg1:number,arg2:api.UpdateCompletedTaskRequest):Promise<void>;

export function UpdateProject(arg1:number,arg2:api.ProjectInput):Promise<void>;
