// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAgentActionProposal(arg1) {
  return window['go']['main']['App']['AcceptAgentActionProposal'](arg1);
}

export function AcceptSummaryActionItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcceptSummaryActionItem'](arg1, arg2, arg3);
}

export function CreateAgentRun(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAgentRun'](arg1, arg2, arg3);
}

export function CreateDailyTask(arg1) {
  return window['go']['main']['App']['CreateDailyTask'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteCompletedTask(arg1) {
  return window['go']['main']['App']['DeleteCompletedTask'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSummary(arg1) {
  return window['go']['main']['App']['DeleteSummary'](arg1);
}

export function EstimateTaskPreview(arg1) {
  return window['go']['main']['App']['EstimateTaskPreview'](arg1);
}

export function FinishTask(arg1, arg2) {
  return window['go']['main']['App']['FinishTask'](arg1, arg2);
}

export function GenerateDailySummary(arg1) {
  return window['go']['main']['App']['GenerateDailySummary'](arg1);
}

export function GenerateWeeklySummary(arg1, arg2) {
  return window['go']['main']['App']['GenerateWeeklySummary'](arg1, arg2);
}

export function GetAgentRun(arg1) {
  return window['go']['main']['App']['GetAgentRun'](arg1);
}

export function GetAgentTrajectory(arg1) {
  return window['go']['main']['App']['GetAgentTrajectory'](arg1);
}

export function GetDailyStats(arg1) {
  return window['go']['main']['App']['GetDailyStats'](arg1);
}

export function GetPlanRisk(arg1) {
  return window['go']['main']['App']['GetPlanRisk'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function GetSummaries(arg1) {
  return window['go']['main']['App']['GetSummaries'](arg1);
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function GetWeeklyStats(arg1, arg2) {
  return window['go']['main']['App']['GetWeeklyStats'](arg1, arg2);
}

export function ListActionItemAcceptances(arg1) {
  return window['go']['main']['App']['ListActionItemAcceptances'](arg1);
}

export function ListAgentActionProposals(arg1) {
  return window['go']['main']['App']['ListAgentActionProposals'](arg1);
}

export function ListAgentRuns(arg1, arg2) {
  return window['go']['main']['App']['ListAgentRuns'](arg1, arg2);
}

export function ListDailyTasks(arg1) {
  return window['go']['main']['App']['ListDailyTasks'](arg1);
}

export function ListMemories(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMemories'](arg1, arg2, arg3);
}

export function ListMemoryEvidence(arg1) {
  return window['go']['main']['App']['ListMemoryEvidence'](arg1);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PreviewAgentContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewAgentContext'](arg1, arg2, arg3);
}

export function RejectAgentActionProposal(arg1) {
  return window['go']['main']['App']['RejectAgentActionProposal'](arg1);
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function SubmitFeedback(arg1) {
  return window['go']['main']['App']['SubmitFeedback'](arg1);
}

export function TestLLM() {
  return window['go']['main']['App']['TestLLM']();
}

export function UpdateCompletedTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateCompletedTask'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}
