// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CreateDailyTask(arg1:api.CreateDailyTaskRequest):Promise<api.CreateResponse>;

export function CreateProject(arg1:api.ProjectInput):Promise<api.CreateResponse>;

export function DeleteProject(arg1:number):Promise<void>;

export function FinishTask(arg1:number):Promise<void>;

export function GetProject(arg1:number):Promise<api.Project>;

export function GetProjects():Promise<Array<api.Project>>;

export function GetStartupStatus():Promise<api.StartupStatus>;

export function ListDailyTasks(arg1:string):Promise<Array<api.DailyTask>>;

export function PauseTask(arg1:number):Promise<void>;

export function ResumeTask(arg1:number):Promise<void>;

export function StartTask(arg1:number):Promise<void>;

export function UpdateProject(arg1:number,arg2:api.ProjectInput):Promise<void>;
